// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
import { Creatures, CreaturesData, CreaturesTableId } from "./tables/Creatures.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
