// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
import { ShopConfig, ShopConfigData, ShopConfigTableId } from "./tables/ShopConfig.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { Creatures, CreaturesData, CreaturesTableId } from "./tables/Creatures.sol";
import { Piece, PieceData, PieceTableId } from "./tables/Piece.sol";
import { Board, BoardData, BoardTableId } from "./tables/Board.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
