// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAutoBattleSystem {
  function autoBattle(
    bytes32[] calldata _ids,
    uint256[2][] calldata _positions,
    uint256 _separate
  ) external returns (uint256);
}
