// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAutoBattleSystem {
  function autoBattle(bytes32 _boardId) external returns (uint256);
}
